name: projetorecuperacaomatheusquost
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  intl: ^0.20.2
  mockito: ^5.6.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
